In [48]:
# import all required libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [49]:
df = pd.read_csv(r"D:\pritish class files\Data Science, ML, AI\DataScience\DataScience\4. Decision-Trees-and-Random-Forests\Social_Network_Ads.csv")

In [50]:
print(df.head())

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0


In [51]:
print(df['Purchased'].unique())

[0 1]


In [52]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB
None


In [53]:
print(df.corr())

                  User ID       Age  EstimatedSalary  Purchased
User ID          1.000000 -0.000721         0.071097   0.007120
Age             -0.000721  1.000000         0.155238   0.622454
EstimatedSalary  0.071097  0.155238         1.000000   0.362083
Purchased        0.007120  0.622454         0.362083   1.000000


In [54]:
df.drop(['User ID'],axis=1,inplace=True)

In [55]:
gender = pd.get_dummies(df['Gender'],drop_first=True)

In [56]:
print(gender.head())

   Male
0     1
1     1
2     0
3     0
4     1


In [57]:
df.drop('Gender',axis=1,inplace=True)

In [58]:
df=pd.concat([df,gender],axis=1)

In [59]:
print(df.head())

   Age  EstimatedSalary  Purchased  Male
0   19            19000          0     1
1   35            20000          0     1
2   26            43000          0     0
3   27            57000          0     0
4   19            76000          0     1


In [60]:
print(df.corr())

                      Age  EstimatedSalary  Purchased      Male
Age              1.000000         0.155238   0.622454 -0.073741
EstimatedSalary  0.155238         1.000000   0.362083 -0.060435
Purchased        0.622454         0.362083   1.000000 -0.042469
Male            -0.073741        -0.060435  -0.042469  1.000000


In [61]:
from sklearn.preprocessing import StandardScaler

In [62]:
scaler = StandardScaler()
scaler.fit(df.drop('Purchased',axis=1))

StandardScaler()

In [63]:
scaled_features = scaler.transform(df.drop('Purchased',axis=1))

In [64]:
df_feat = pd.DataFrame(scaled_features,columns=['Age','EstimatedSalary','Male'])

In [65]:
print(df_feat.head())

        Age  EstimatedSalary      Male
0 -1.781797        -1.490046  1.020204
1 -0.253587        -1.460681  1.020204
2 -1.113206        -0.785290 -0.980196
3 -1.017692        -0.374182 -0.980196
4 -1.781797         0.183751  1.020204


In [66]:
print(df.corr())

                      Age  EstimatedSalary  Purchased      Male
Age              1.000000         0.155238   0.622454 -0.073741
EstimatedSalary  0.155238         1.000000   0.362083 -0.060435
Purchased        0.622454         0.362083   1.000000 -0.042469
Male            -0.073741        -0.060435  -0.042469  1.000000


In [67]:
df.drop(['Male'],axis=1,inplace=True)

In [68]:
print(df.head())

   Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0


In [69]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df_feat,df['Purchased'],test_size=0.30,random_state=60)

In [70]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier.fit(x_train,y_train)

DecisionTreeClassifier()

In [71]:
y_pred = classifier.predict(x_test)

In [72]:
y_pred

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1], dtype=int64)

In [73]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [74]:
print(confusion_matrix(y_test,y_pred))

[[78  4]
 [14 24]]


In [75]:
print(accuracy_score(y_test,y_pred))

0.85


In [100]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=100)
rfc.fit(x_train,y_train)

RandomForestClassifier()

In [101]:
rfc_pred = rfc.predict(x_test)

In [102]:
rfc_pred

array([0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1], dtype=int64)

In [103]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [104]:
print(confusion_matrix(y_test,rfc_pred))

[[78  4]
 [ 8 30]]


In [105]:
print(accuracy_score(y_test,y_pred))

0.85
